# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26f61e7651d819c578ed8d40df182e024a468b4d03f007e06dc82441d382e7a5800b21e5d21872b0e81b8d2a32fae52924a4c56e99c0463b536c82bd5dbdbef

test:
  secret_key_base: f4f9bb856a37dbf0fa4af6270c374744b31979e233ee61c120949a9de90dfec0f60422b7459ca32e869e71582cd3095c65b1c8325a9108e0a697857a4d4f67c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
